### PR TITLE
help command added.

### PR DESCRIPTION
**Pull request by prabhakaran9397**

### CODE REVIEW

**Comment by mumararshaikh** [comment]
Also provide description for your changes.

**Comment by Idnan** [comment]
@prabhakaran9397 the description is not clear and also the example is not good. Please make the description and example clear.

**Comment by Idnan** [comment]
@prabhakaran9397 the description is not clear and also the example is not good. Please make the description and example clear.

**Comment by Idnan** [comment]
@prabhakaran9397 I am closing the PR. Reopen in case the fixes are done.

**Pull request closed without merging**
